spring.application.name=vibe_guide

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vibe_guide?sslmode=disable}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:5}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:1}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/master.xml
spring.liquibase.url=${SPRING_LIQUIBASE_URL:${spring.datasource.url}}
spring.liquibase.user=${SPRING_LIQUIBASE_USER:${spring.datasource.username}}
spring.liquibase.password=${SPRING_LIQUIBASE_PASSWORD:${spring.datasource.password}}

app.storage.cloudinary-folder=${APP_STORAGE_CLOUDINARY_FOLDER:vibe-guide-demo}
