name: Maven Build

on:
  push:
    branches:
      - '**'  # Runs on push to all branches
  pull_request:
    branches:
      - '**'  # Runs on pull request to all branches

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 15881577.p
          POSTGRES_DB: vibe_guide
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
    strategy:
      matrix:
        java-version: [23]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..10}; do
            nc -zv localhost 5432 && echo "PostgreSQL is ready!" && break
            echo "Waiting for PostgreSQL..."
            sleep 10
          done

      - name: Run tests
        run: mvn clean install